'use client';

import React from 'react';
import { Info, HelpCircle, ShieldCheck, Cpu, Layers, Sparkles, AlertTriangle } from 'lucide-react';

export const RadarExplanatoryGuide: React.FC = () => {
  return (
    <div className="panel-surface p-5 text-slate-100 space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-3">
        <div className="flex items-center space-x-2.5">
          <div className="p-2 bg-sky-950/80 border border-sky-800/80 rounded-xl text-sky-400">
            <HelpCircle className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-extrabold text-slate-100 uppercase tracking-wider">
              How to Read this Radar
            </h3>
            <p className="text-[11px] text-slate-400">
              Methodology & automated viability scoring framework
            </p>
          </div>
        </div>
        <span className="text-[10px] text-slate-400 font-semibold uppercase tracking-wider bg-slate-900 border border-slate-800 px-2.5 py-1 rounded-lg">
          Intelligence Guide
        </span>
      </div>

      {/* 4 Step Methodology Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3 text-xs">
        {/* Step 1 */}
        <div className="p-3.5 bg-[#060a12]/80 border border-slate-800/80 rounded-xl space-y-1.5">
          <div className="flex items-center space-x-2 text-sky-400 font-bold">
            <Cpu className="w-4 h-4 shrink-0" />
            <span>1. Global Ingestion</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Continuous NLP ingestion of global GDELT events, filtering policy, CapEx, regulatory, and industrial news.
          </p>
        </div>

        {/* Step 2 */}
        <div className="p-3.5 bg-[#060a12]/80 border border-slate-800/80 rounded-xl space-y-1.5">
          <div className="flex items-center space-x-2 text-amber-400 font-bold">
            <Layers className="w-4 h-4 shrink-0" />
            <span>2. Story Clustering</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Aggregating related events across geographies into high-momentum thematic story clusters and sector hubs.
          </p>
        </div>

        {/* Step 3 */}
        <div className="p-3.5 bg-[#060a12]/80 border border-slate-800/80 rounded-xl space-y-1.5">
          <div className="flex items-center space-x-2 text-emerald-400 font-bold">
            <ShieldCheck className="w-4 h-4 shrink-0" />
            <span>3. Viability Scoring</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Multi-factor scoring combining Feasibility, Impact, and Time-to-Market into High, Medium, & Low likelihood bands.
          </p>
        </div>

        {/* Step 4 */}
        <div className="p-3.5 bg-[#060a12]/80 border border-slate-800/80 rounded-xl space-y-1.5">
          <div className="flex items-center space-x-2 text-sky-400 font-bold">
            <Sparkles className="w-4 h-4 shrink-0" />
            <span>4. AI Co-Pilot Context</span>
          </div>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Interactive AI due diligence co-pilot assisting with GTM strategies, capital estimation, and risk analysis.
          </p>
        </div>
      </div>

      {/* AI Disclaimer Notice Banner */}
      <div className="p-3 bg-[#060a12] border border-slate-800 rounded-xl text-[11px] text-slate-400 flex items-center justify-between">
        <div className="flex items-center space-x-2">
          <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
          <span>
            <strong className="text-slate-200 font-semibold">AI Disclaimer:</strong> Opportunity scores and strategic analyses are generated by computational models from public news streams. Not financial, legal, or investment advice.
          </span>
        </div>
      </div>
    </div>
  );
};
